---
- name: Install MongoDB 3.2
  hosts: db
  become: true
  tasks:
  # Добавим ключ репозитория для последующей работы с ним
 
  # Выполним установку пакета
  - name: Install mongodb package
    apt:
      name: mongodb-org
      state: present

  # Включаем сервис
  - name: Configure service supervisor
    systemd:
      name: mongod
      enabled: yes
      